name: CI Test Workflow

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 22f1001403@ds.study.iitm.ac.in
        run: echo "Hello, world!"
